global:
  scrape_interval: 5s  # Fréquence de récupération des données

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'  # Récupérer les infos d'une machine
    static_configs:
      - targets: ['192.168.1.100:9100']  # IP d'un serveur à monitorer

  - job_name: 'docker_metrics'
    static_configs:
      - targets: ['host.docker.internal:9323']
