global:
  scrape_interval: 5s  # Fréquence de récupération des données

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'  # Récupérer les infos de cette machine
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'docker_metrics'
    static_configs:
      - targets: ['host.docker.internal:9323']
